<%@ Page Title="" Language="C#" MasterPageFile="~/Visual.Master" AutoEventWireup="true" CodeBehind="CarritoCompras.aspx.cs" Inherits="PRESENTACION.CarritoCompras" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="div_principal">
        <div>
            <asp:Label ID="Label2" runat="server" Text="Carrito de compras"></asp:Label>
            <br />
            <asp:GridView ID="gvCarrito" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True">
                <Columns>
                    <asp:TemplateField HeaderText="Juego">
                        <ItemTemplate>
                            <asp:Label ID="lblNombreJuego" runat="server"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Precio">
                        <ItemTemplate>
                            <asp:Label ID="lblPrecio" runat="server"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Desarrollador">
                        <ItemTemplate>
                            <asp:Label ID="lblDesarrollador" runat="server"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Genero">
                        <ItemTemplate>
                            <asp:Label ID="lblGenero" runat="server"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
            <br />
            <asp:Label ID="lblTotal" runat="server"></asp:Label>
            <br />
            <br />
            <asp:Label ID="Label1" runat="server" Text="Seleione un medio de pago"></asp:Label>
            <asp:DropDownList ID="ddlMedios" runat="server"></asp:DropDownList>
            <br />
            <asp:Button ID="btnAceptar" runat="server" Text="Comprar" />            
            <br />
            <br />
            <asp:LinkButton ID="lbSeguirComprando" runat="server">Seguir comprando</asp:LinkButton>
        </div>
    </div>
</asp:Content>
