<%@ Page Title="" Language="C#" MasterPageFile="~/Admi.Master" AutoEventWireup="true" CodeBehind="FormReview.aspx.cs" Inherits="PRESENTACION.FormReview" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
            <div id="div_label">
        <asp:Label ID="Label2" runat="server" Text="Administrar Reviews" Font-Size="X-Large" Font-Underline="True"></asp:Label>
    </div>
    <div class="Label">
        <asp:Label ID="Label3" runat="server" Text="Listado de reviews" Font-Bold="True"></asp:Label>
    </div>
    <div>
        <asp:GridView ID="gvReviews" runat="server" AllowPaging="True" AutoGenerateColumns="False" PageSize="5" CssClass="auto-style5" OnPageIndexChanging="gvReviews_PageIndexChanging" AutoGenerateDeleteButton="True" OnRowDeleting="gvReviews_RowDeleting">
            <Columns>
                <asp:TemplateField HeaderText="Codigo de review">
                    <ItemTemplate>
                        <asp:Label ID="lblCod" runat="server" Text='<%# Bind("Cod_Review") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Codigo de juego">
                    <ItemTemplate>
                        <asp:Label ID="lblJuego" runat="server" Text='<%# Bind("id_juego") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Usuario">
                    <ItemTemplate>
                        <asp:Label ID="lblUsuario" runat="server" Text='<%# Bind("Cod_Usuario") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Review">
                    <ItemTemplate>
                        <asp:Label ID="lblReview" runat="server" Text='<%# Bind("Review") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
            <HeaderStyle BackColor="Red" />
            <PagerStyle BackColor="Red" />
            <RowStyle HorizontalAlign="Center" />
        </asp:GridView>
    </div>
</asp:Content>
