CREATE PROCEDURE spActualizarUsuario
(
@USUARIO NVARCHAR(50),
@NOMBRE NVARCHAR(50),
@APELLIDO NVARCHAR(50),
@EMAIL NVARCHAR(50),
@CONTRASEÑA NVARCHAR(50),
@TELEFONO NVARCHAR (50),
@COD_PAIS INT,
@ADMINISTRADOR BIT
)
AS
UPDATE Usuario
SET
Nombre=@NOMBRE,
Apellido=@APELLIDO,
Email=@EMAIL,
Telefono=@TELEFONO,
Cod_Pais=@COD_PAIS,
Administrador=@ADMINISTRADOR
WHERE Usuario=@USUARIO
RETURN
GO