CREATE PROCEDURE spEliminarUsuario
(
@USUARIO NVARCHAR(50),
@NOMBRE NVARCHAR(50),
@APELLIDO NVARCHAR(50),
@EMAIL NVARCHAR(50),
@CONTRASEÑA NVARCHAR(50),
@TELEFONO NVARCHAR (50),
@COD_PAIS INT,
@ADMINISTRADOR BIT
)
AS
DELETE Usuario WHERE Usuario=@USUARIO
RETURN